### ISSUE TITLE
[Feature request] Analyzer: respect `exclude` from `analysis_options.yaml` file

### ISSUE THREAD

**Issue by cedx** [google/grinder.dart#346]
In my `analysis_options.yaml` file, I have:

```yaml
analyzer:
  exclude:
    - lib/**.g.dart
    - lib/src/version.dart
```

The analysis server says that everything is OK, but the `Analyzer.analyze()` method triggers this error:

```
No dart files found at: [...]\lib\src\cli.g.dart
```

The `Analyzer.analyze()` method should report the same errors as the analysis server by ignoring the file patterns declared in `analysis_options.yaml` file.
